---
- name: Download and install nfs packages
  yum: name={{ item }} state=present
  with_items: nfs_packages
  when: ansible_os_family == 'RedHat'

- name: Download and install nfs packages
  apt: name={{ item }} state=present
  with_items: nfs_packages
  when: ansible_os_family == 'Debian'

- name: Ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes
  when: ansible_os_family == 'RedHat'

- name: Create the /etc/exports file
  template: src=nfs/exports.j2 dest=/etc/exports owner=root group=root mode=0644
  notify: restart nfs

- name: Create the AstrixDB NFS export directory
  file: path={{ asterixdb_data_dir }}{{ asterixdb_working_dir }} state=directory owner=asterixdb group=asterixdb mode=0755

- name: Ensure nfs is running
  service: name={{ nfs_server_daemon }} state=started enabled=yes
